### ISSUE TITLE
Tokenizer training data 

### ISSUE THREAD

**Issue by amishparekh** [AnswerDotAI/ModernBERT#150]
Hi,
Thanks for the amazing work. Could you let me know the data used to train the tokenizer and which is the tokenizer used?

**Comment by warner-benjamin** [comment]
As we mention in our [paper](https://arxiv.org/abs/2412.13663), we use the OLMo tokenizer with a few light modifications:
> We use a modified version of the OLMo tokenizer (Groeneveld et al., 2024) which provides better token efficiency and performance on coderelated tasks. The ModernBERT tokenizer uses the same special tokens (e.g., [CLS] and [SEP]) and templating as the original BERT model (Devlin et al., 2019), facilitating backwards compatibility. To ensure optimal GPU utilization (Anthony et al., 2024; Karpathy, 2023), the vocabulary is set to 50,368, a multiple of 64 and includes 83 unused tokens to support downstream applications.
