### ISSUE TITLE
what is the difference between mGTE？

### ISSUE THREAD

**Issue by rangehow** [AnswerDotAI/ModernBERT#159]
https://arxiv.org/abs/2407.19669

**Comment by NohTow** [comment]
mGTE is a multilingual model that introduced some of the improvements we also introduced in ModernBERT.
They also trained an English version, to which we compare (gte-en-MLM). 
We introduce further improvements (e.g alternating attention) and train on a way bigger and diverse dataset than them, which allows ModernBERT to be faster and achieve better results on almost every tasks.

Please refer to the paper for more comparison.
