### ISSUE TITLE
KeyError when importing in google colab 

### ISSUE THREAD

**Issue by delalamo** [AnswerDotAI/ModernBERT#167]
At least with the free version of google colab (T4 GPU), and up-to-date transformers library and python 3.10, ModernBERT cannot be loaded. Screenshot below, Jupyter notebook link here: https://colab.research.google.com/drive/1U9NDEcdmhQunDTNXdzqWtoYpp2_rjNxe?usp=sharing

<img width="1432" alt="image" src="https://github.com/user-attachments/assets/2b4c6e7c-8681-4a5b-8148-ba2c5e8bfa5c" />

Error text (for search purposes):
```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py](https://localhost:8080/#) in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
   1037             try:
-> 1038                 config_class = CONFIG_MAPPING[config_dict["model_type"]]
   1039             except KeyError:

3 frames
KeyError: 'modernbert'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/transformers/models/auto/configuration_auto.py](https://localhost:8080/#) in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
   1038                 config_class = CONFIG_MAPPING[config_dict["model_type"]]
   1039             except KeyError:
-> 1040                 raise ValueError(
   1041                     f"The checkpoint you are trying to load has model type `{config_dict['model_type']}` "
   1042                     "but Transformers does not recognize this architecture. This could be because of an "

ValueError: The checkpoint you are trying to load has model type `modernbert` but Transformers does not recognize this architecture. This could be because of an issue with the checkpoint, or because your version of Transformers is out of date.
```

EDIT updated to fix screenshot

**Comment by amaarora** [comment]
Try installing packages in this order:
```
!pip install git+https://github.com/lightonai/pylate.git
!pip install git+https://github.com/UKPLab/sentence-transformers.git
!pip install git+https://github.com/huggingface/transformers.git
```

**Comment by NohTow** [comment]
Hello,

As the release of transformers including ModernBERT has not been pushed upstream, you have to install transformers from main to use ModernBERT for now, as mentioned in #145.
You can use `pip install git+https://github.com/huggingface/transformers.git` (with the ! if you are in collab) to do so.

As mentioned by @amaarora, if you want to use it with PyLate or ST (or any library depending on transformers with a strict `==`dependency), please install it after those as they will override the version of transformers.

**Comment by caocongfeng** [comment]
I am facing this problem even after following the above suggestions.
