### ISSUE TITLE
No sentence-transformers model found with name answerdotai/ModernBERT-base. Creating a new one with mean pooling.

### ISSUE THREAD

**Issue by amaarora** [AnswerDotAI/ModernBERT#168]
When I run the `train_st.py` script - I get 
> No sentence-transformers model found with name answerdotai/ModernBERT-base. Creating a new one with mean pooling.

Is this expected?

**Comment by NohTow** [comment]
Yes,
ModernBERT is a base model, not a sentence-transformers model, so when creating a ST model with `answerdotai/ModernBERT-base`, it takes the base model and add a pooling layer, here a mean pooling one.

If you then load the model you trained (or one someone else trained, such as [this one](https://huggingface.co/NohTow/ModernBERT-base-DPR-fullneg-gte-0.0002), [this one](https://huggingface.co/tasksource/ModernBERT-base-embed) or [this one](https://huggingface.co/tomaarsen/ModernBERT-base-gooaq), it won't print such message.

**Comment by amaarora** [comment]
Thank you so much @NohTow !
